//go:build ignore

// Copyright 2026 The many-ai-cli authors.
// Generate pinned Go Unicode data and synthetic regex observations; no policy,
// home, provider, network, repository, or user data is opened by this program.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"regexp/syntax"
	"runtime"
	"sort"
	"strings"
	"unicode"
)

var sourceHashes = map[string]string{
	"VERSION":                          "25b231b380ff42bb887b29e7c2eb176167820f3416665cd4fbc2d3b116bc417d",
	"LICENSE":                          "911f8f5782931320f5b8d1160a76365b83aea6447ee6c04fa6d5591467db9dad",
	"src/unicode/tables.go":            "6a88d48746c4b2c471cc04ae40559694b734770212e6f5ea5f1962adb0c0bdb1",
	"src/unicode/letter.go":            "b35a6d259313cef88d07e9e4027b8bd72c60ae140418f5be2c41a2ecea6074fe",
	"src/regexp/syntax/parse.go":       "d0f657113901da39d6118e4172206a0358b71c96ef43051cc0a741a0a4d04820",
	"src/regexp/syntax/perl_groups.go": "d060a0645b60b210eaec7c3dba6d554dc297c14fe71cdbcc9c25b4fc7562c3a4",
	"src/regexp/exec.go":               "cc9fda63ad7056d4c4abaaa49c00470f726be35ccee53f1c3fe73259e9634dd5",
	"src/regexp/onepass.go":            "fd0e29803438c6ea3021c78227d4f69de163f693e82c155dc62d721eaacbd24b",
	"src/regexp/regexp.go":             "addd07fbda0b622c063e0f5516b55c684d48ab9cc5d3a4a9f90d82b19c527772",
	"src/regexp/backtrack.go":          "ac5a1e4cf49b1c7f4372c0a7c2e8d156100c17d3a114fcf9539f55d223d06092",
	"src/regexp/syntax/compile.go":     "2e1f753be77bf1fa54aed2a7f98932394324b82c91109e19d93283f482f7ee01",
	"src/regexp/syntax/prog.go":        "7a24ebd22eec504ceaeffbd33641ae330d3ca666d54f6a29ce6d96fc127e6c64",
	"src/regexp/syntax/regexp.go":      "72fad4645d96cf8b0ef0ea4a9dae21f09e7bea090d1bdd500732d811982b2192",
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
func canonical(s string) string {
	return strings.ToLower(strings.NewReplacer("_", "", "-", "", " ", "").Replace(s))
}
func ranges(re *syntax.Regexp) []rune {
	switch re.Op {
	case syntax.OpCharClass:
		return re.Rune
	case syntax.OpAnyChar:
		return []rune{0, unicode.MaxRune}
	case syntax.OpAnyCharNotNL:
		return []rune{0, 9, 11, unicode.MaxRune}
	case syntax.OpNoMatch:
		return []rune{}
	case syntax.OpLiteral:
		if len(re.Rune) != 1 {
			panic(re.String())
		}
		r := re.Rune[0]
		rs := []rune{r}
		if re.Flags&syntax.FoldCase != 0 {
			for f := unicode.SimpleFold(r); f != r; f = unicode.SimpleFold(f) {
				rs = append(rs, f)
			}
		}
		sort.Slice(rs, func(i, j int) bool { return rs[i] < rs[j] })
		out := []rune{}
		for _, x := range rs {
			out = append(out, x, x)
		}
		return out
	default:
		panic(fmt.Sprint(re.Op))
	}
}
func property(name string, fold bool) []rune {
	p := `\p{` + name + `}`
	if fold {
		p = "(?i)" + p
	}
	re, err := syntax.Parse(p, syntax.Perl)
	must(err)
	return ranges(re)
}
func emitRanges(b *strings.Builder, r []rune) {
	b.WriteString("&[")
	for i := 0; i < len(r); i += 2 {
		fmt.Fprintf(b, "(0x%x,0x%x),", r[i], r[i+1])
	}
	b.WriteString("]")
}

type Observation struct {
	Pattern string   `json:"pattern"`
	Values  []string `json:"values"`
	Valid   bool     `json:"valid"`
	Matches []bool   `json:"matches"`
}

func observe(pattern string, values []string) Observation {
	o := Observation{Pattern: pattern, Values: values, Matches: []bool{}}
	re, err := regexp.Compile(pattern)
	o.Valid = err == nil
	if err == nil {
		for _, v := range values {
			o.Matches = append(o.Matches, re.MatchString(v))
		}
	}
	return o
}
func main() {
	if len(os.Args) != 3 {
		panic("usage: generate.go <tables.rs> <fixture-directory>")
	}
	if runtime.Version() != "go1.26.8" || unicode.Version != "15.0.0" {
		panic("requires Go 1.26.8 / Unicode 15.0.0")
	}
	for p, want := range sourceHashes {
		data, err := os.ReadFile(filepath.Join(runtime.GOROOT(), p))
		must(err)
		sum := sha256.Sum256(data)
		if hex.EncodeToString(sum[:]) != want {
			panic("pinned source hash mismatch: " + p)
		}
	}
	names := map[string]string{"any": "Any", "ascii": "ASCII", "assigned": "Assigned"}
	for k := range unicode.Categories {
		names[canonical(k)] = k
	}
	for k := range unicode.Scripts {
		names[canonical(k)] = k
	}
	rejectedNames := []string{}
	for k, v := range names {
		if _, err := syntax.Parse(`\p{`+v+`}`, syntax.Perl); err != nil {
			rejectedNames = append(rejectedNames, v)
			delete(names, k)
		}
	}
	sort.Strings(rejectedNames)
	keys := []string{}
	for k := range names {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("// @generated by autoapproval-unicode/generate.go; do not hand-edit.\n// Go 1.26.8 / Unicode 15.0.0. Go-derived data: see GO-LICENSE.\n// Source hashes and regeneration contract: fixture README.md and provenance.json.\n// Explicit rune intervals include surrogate values; emission clips to Rust scalars.\n\n")
	b.WriteString("type Property = (&'static str, &'static [(u32, u32)], &'static [(u32, u32)]);\n\n#[rustfmt::skip]\npub(super) static PROPERTIES: &[Property] = &[\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "(%q,", k)
		emitRanges(&b, property(names[k], false))
		b.WriteString(",")
		emitRanges(&b, property(names[k], true))
		b.WriteString("),\n")
	}
	b.WriteString("];\n\n")
	aliases := map[string]string{}
	for alias, actual := range unicode.CategoryAliases {
		aliases[canonical(alias)] = canonical(actual)
	}
	keys = keys[:0]
	for k := range aliases {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	b.WriteString("#[rustfmt::skip]\npub(super) static ALIASES: &[(&str,&str)] = &[\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "(%q,%q),\n", k, aliases[k])
	}
	b.WriteString("];\n\n")
	b.WriteString("#[rustfmt::skip]\npub(super) static SIMPLE_FOLD: &[(u32, u32)] = &[\n")
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if f := unicode.SimpleFold(r); f != r {
			fmt.Fprintf(&b, "(0x%x,0x%x),\n", r, f)
		}
	}
	b.WriteString("];\n")
	must(os.WriteFile(os.Args[1], []byte(b.String()), 0644))
	lic, err := os.ReadFile(filepath.Join(runtime.GOROOT(), "LICENSE"))
	must(err)
	must(os.WriteFile(filepath.Join(filepath.Dir(os.Args[1]), "GO-LICENSE"), lic, 0644))
	provenance := map[string]any{"go_version": runtime.Version(), "unicode_version": unicode.Version, "go_behavior_baseline": "21d0bc7935a2c4696fb89ccff2e324157a528c2d", "source_base": "https://go.googlesource.com/go/+/refs/tags/go1.26.8/", "source_sha256": sourceHashes}
	data, err := json.MarshalIndent(provenance, "", "  ")
	must(err)
	must(os.WriteFile(filepath.Join(os.Args[2], "provenance.json"), append(data, '\n'), 0644))
	observations := []Observation{}
	for _, name := range rejectedNames {
		observations = append(observations, observe(`\p{`+name+`}`, []string{"a", "日"}))
	}
	values := []string{"", "a", "A", "K", "k", "K", "S", "s", "ſ", "ß", "ẞ", "λ", "Λ", "σ", "ς", "Σ", "İ", "ı", "i", "I", "𐐀", "𐐨", "𞤀", "𞤢", "日", "\n", "\r", "\v", "\u00a0", "\ufffd", "\U00001c89", "\U00001c8a", "\U0002ebf0", "\U00031350", "\U000323b0", "\U00010ffff"}
	// Each property and alias exercises actual regexp matching on its interval
	// boundaries, neighbors, fold partners, and representative version sentinels.
	namesToCheck := map[string]bool{}
	for _, v := range names {
		namesToCheck[v] = true
	}
	for k := range unicode.CategoryAliases {
		namesToCheck[k] = true
	}
	keys = keys[:0]
	for k := range namesToCheck {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, name := range keys {
		sample := map[rune]bool{}
		for _, fold := range []bool{false, true} {
			rs := property(name, fold)
			for _, r := range rs {
				for _, x := range []rune{r - 1, r, r + 1} {
					if x >= 0 && x <= unicode.MaxRune && !(x >= 0xd800 && x <= 0xdfff) {
						sample[x] = true
					}
				}
			}
		}
		runes := []rune{}
		for r := range sample {
			runes = append(runes, r)
		}
		sort.Slice(runes, func(i, j int) bool { return runes[i] < runes[j] })
		vs := append([]string{}, values...)
		for _, r := range runes {
			vs = append(vs, string(r))
		}
		for _, prefix := range []string{"", "(?i)"} {
			for _, kind := range []string{`\p{`, `\P{`} {
				observations = append(observations, observe(prefix+"^"+kind+name+"}$", vs))
			}
		}
	}
	for _, p := range []string{
		`(?i)^λ$`, `(?i)^𐐀$`, `(?i)^ß$`, `(?i)^İ$`, `(?i)^ı$`, `(?i)^k$`, `(?i)^s$`, `(?i)^\x{1c89}$`, `(?i)^\Qλ.Σ\E$`,
		`(?i)^[a-z]$`, `(?i)^[^a-z]$`, `(?i)^[[:upper:]]$`, `(?i)^[[:^upper:]]$`, `(?i)^[\W]$`, `(?i)^\w$`, `(?i)^\P{Lu}$`, `(?i)^[\P{Lu}A]$`,
		`^\p{surrogate}$`, `^\P{Cs}$`, `^\p{^Han}$`, `^\P{^Han}$`, `^\p{ l_o_w_e_r-c a s e l e t t e r }$`, `^\pL$`, `^\p{Alphabetic}$`, `^\p{Script=Latin}$`, `^\p{L\t}$`,
		`^cat \x{d800}$`, `^\x{d800}\x{dfff}$`, `^a(?:)\x{d800}$`, `^(?:)\x{d800}$`, `^\x{fffd}\x{d800}$`, `^\x{d800}\x{fffd}$`, `^[\x{d800}]$`, `^[\x{d800}-\x{d800}]$`, `\x{d800}`, `(?m)^\x{d800}$`, `^\x{d800}`, `^\x{d800}$`, `^\x{d800}?$`, `^\x{d800}*$`, `^\x{d800}|a$`, `^[^\x{d800}]$`, `^[\x{d7ff}-\x{e000}]$`, `^[\x{d800}-\x{dfff}]$`, `^[\x{d800}-\x{10ffff}]$`, `(?i)^[\x{d800}-\x{e000}]$`, `^\x{000000000000000000000061}$`,
		`(?i:a)(?-i:b)(?i:c)`, `(?i)λ(?-i:λ)λ`, `(?i:λ)λ`, `(?i)λ|λ`, `a*(?i)*`, `a*(?)*`, `a*\Q\E*`, `^*`, `$+`, `(?:)*`, `a(?i)*`, `(?i)*`, `a|*`, `a|(?i)*`, `(?i-i)^a$`, `(?-)a`, `(?-:)a`,
		`a{0}(a{1000}){2}`, `(a{1000}){0}`, `(a{1000}){0,}`, `((a{1000}){0}){1000}`, `(((a{1000}){0}){1000}){2}`, `((?:){1000}){1000}`, `((a{1000}){0,}){2}`, `[[:bogus:]]`, `[[:alpha]`, `[a-\pL]`, `[\pL-a]`, `[\x{dfff}-\x{d800}]`,
	} {
		vs := append([]string{}, values...)
		vs = append(vs, "abc", "ABC", "AbC", "ΛλΛ", "ΛΛΛ", "Λλ", "λλ", "λΣ", "Λ.ς", "a*", "aa", "cat �", "��", "a�", "�a", "[", "a-", "a\n", "\n")
		observations = append(observations, observe(p, vs))
	}

	// Exercise every nontrivial SimpleFold orbit through the public regexp
	// matcher, including each singleton and range/complement spelling.
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if unicode.SimpleFold(r) == r {
			continue
		}
		vs := []string{string(r), "", "0", "\U00001c89", "\U00001c8a"}
		for f := unicode.SimpleFold(r); f != r; f = unicode.SimpleFold(f) {
			vs = append(vs, string(f))
		}
		for _, neighbor := range []rune{r - 1, r + 1} {
			if neighbor >= 0 && neighbor <= unicode.MaxRune && !(neighbor >= 0xd800 && neighbor <= 0xdfff) {
				vs = append(vs, string(neighbor))
			}
		}
		for _, pattern := range []string{fmt.Sprintf(`(?i)^\x{%x}$`, r), fmt.Sprintf(`(?i)^[^\x{%x}]$`, r)} {
			observations = append(observations, observe(pattern, vs))
		}
	}
	// Deterministic syntax compositions exercise flag scope, empty atoms,
	// repetitions, assertions, grouping and class membership together.
	for _, atom := range []string{`a`, `λ`, `\x{d800}`, `[a-z]`, `\p{Lu}`, `\P{ASCII}`, `^`, `$`, `\b`, `(?:)`} {
		for _, quantifier := range []string{"", "*", "+", "?", "{0}", "{2}", "{2,}"} {
			for _, prefix := range []string{"", "(?i)", "(?m)", "(?s)", "(?i-i)"} {
				vs := append([]string{}, values...)
				vs = append(vs, "aa", "AA", "aA", "λλ", "Λλ", "a\na", "\n\n", "aλa")
				observations = append(observations, observe(prefix+"^(?:"+atom+")"+quantifier+"$", vs))
			}
		}
	}
	data, err = json.Marshal(observations)
	must(err)
	must(os.WriteFile(filepath.Join(os.Args[2], "go_oracle.json"), append(data, '\n'), 0644))
	fmt.Fprintf(os.Stderr, "generated %d properties, %d aliases, %d regex observations\n", len(names), len(aliases), len(observations))
}
