// Synthetic, standard-library-only Go strconv.Quote compatibility oracle.
// Run only with the pinned toolchain; no application packages or real data.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"runtime"
	"strconv"
	"unicode"
	"unicode/utf8"
)

const baseline = "21d0bc7935a2c4696fb89ccff2e324157a528c2d"

type quoteCase struct {
	Name  string `json:"name"`
	Input string `json:"input"`
	Quote string `json:"quote"`
}

type corpus struct {
	Baseline             string      `json:"baseline"`
	GoVersion            string      `json:"go_version"`
	UnicodeVersion       string      `json:"unicode_version"`
	ValidScalarCount     int         `json:"valid_scalar_count"`
	PrintableScalarCount int         `json:"printable_scalar_count"`
	AllScalarQuoteSHA256 string      `json:"all_scalar_quote_sha256"`
	Cases                []quoteCase `json:"cases"`
}

func main() {
	ranges := flag.Bool("ranges", false, "emit the Rust non-ASCII printable range table")
	flag.Parse()
	if runtime.Version() != "go1.26.8" || unicode.Version != "15.0.0" {
		fmt.Fprintln(os.Stderr, "requires go1.26.8 / Unicode 15.0.0")
		os.Exit(1)
	}
	if *ranges {
		emitRanges()
		return
	}
	out := corpus{Baseline: baseline, GoVersion: runtime.Version(), UnicodeVersion: unicode.Version}
	add := func(name, input string) {
		out.Cases = append(out.Cases, quoteCase{Name: name, Input: input, Quote: strconv.Quote(input)})
	}
	add("empty", "")
	add("quotes-backslash-single-quote-backtick", "\"\\'`")
	var ascii, c0, c1 []rune
	for r := rune(0); r < 128; r++ {
		ascii = append(ascii, r)
		if r < 32 || r == 127 {
			add(fmt.Sprintf("ascii-control-U+%04X", r), string(r))
			c0 = append(c0, r)
		}
	}
	for r := rune(128); r < 160; r++ {
		add(fmt.Sprintf("c1-control-U+%04X", r), string(r))
		c1 = append(c1, r)
	}
	add("all-ascii", string(ascii))
	add("all-c0-controls-and-del", string(c0))
	add("all-c1-controls", string(c1))
	for _, r := range []rune{
		// Go printable means L/M/N/P/S plus ASCII space, not all Zs.
		0x20, 0xa0, 0xad, 0x300, 0x34f, 0x378, 0x379, 0x61c,
		0x903, 0x1680, 0x180e, 0x2000, 0x2001, 0x2002, 0x2003,
		0x2004, 0x2005, 0x2006, 0x2007, 0x2008, 0x2009, 0x200a,
		0x200b, 0x200c, 0x200d, 0x200e, 0x200f, 0x2028, 0x2029,
		0x202a, 0x202b, 0x202c, 0x202d, 0x202e, 0x202f, 0x205f,
		0x2060, 0x2061, 0x2062, 0x2063, 0x2064, 0x2065, 0x2066,
		0x2067, 0x2068, 0x2069, 0x206a, 0x206f, 0x3000, 0xd7ff,
		// Private-use, noncharacters, replacement, variation selectors.
		0xe000, 0xf8ff, 0xfdd0, 0xfdef, 0xfe00, 0xfe0f, 0xfeff,
		0xfff9, 0xfffa, 0xfffb, 0xfffc, 0xfffd, 0xfffe, 0xffff,
		0x10000, 0x110bd, 0x110cd, 0x1d173, 0x1d17a,
		0xe0001, 0xe0020, 0xe007f, 0xe0100, 0xe01ef,
		0xf0000, 0xffffd, 0xffffe, 0xfffff, 0x100000, 0x10fffd, 0x10fffe, 0x10ffff,
		// Unicode 15 assignments and neighboring/future assignments.
		0x0cf3, 0x0ece, 0x11f00, 0x11f02, 0x1e4d0, 0x1fae8,
		0x3134a, 0x3134b, 0x31350, 0x323af, 0x323b0,
		0x2ebf0, 0x2ee5d, 0x1c89, 0x1c8a, 0x105c0, 0x11380,
		0x1cc00, 0x1e5d0, 0x1fae9, 0x1faea,
	} {
		add(fmt.Sprintf("unicode-U+%04X", r), string(r))
	}
	add("printable-multilingual", "café Ελληνικά 日本語 한글 😀 © €")
	add("combining-spacing-and-enclosing-marks", "e\u0301\u034f क\u0903 x\u20dd")
	add("emoji-sequence-with-joiner-and-variation", "👩\u200d💻 ✈\ufe0f")
	add("subscription-id-formatting", "work\u00ad\u200f\u2066profile")
	add("subscription-id-private-unassigned", "work\ue000\u0378\U0001fae9")
	add("multiline-crlf-tab", "line one\r\n\tline two\nline three\r")
	add("error-detail", "invalid subscription \"synthetic\": field\tcontains\ncontrol\x00bytes")
	add("profile-leading-dash", "-synthetic\n\u200eprofile")
	add("handoff-subject", "fix \"synthetic\" path C:\\work\\repo\n次の手順\u2028review")
	add("shell-looking-plain-text", "$(synthetic) `literal` ; & < > ' \" \\ \n")
	add("literal-escape-text", `\a\b\f\n\r\t\v\x00\u2028\U0001fae9`)

	digest := sha256.New()
	for r := rune(0); r <= utf8.MaxRune; r++ {
		if !utf8.ValidRune(r) {
			continue
		}
		out.ValidScalarCount++
		if strconv.IsPrint(r) {
			out.PrintableScalarCount++
		}
		_, _ = digest.Write([]byte(strconv.Quote(string(r))))
	}
	out.AllScalarQuoteSHA256 = hex.EncodeToString(digest.Sum(nil))
	encoder := json.NewEncoder(os.Stdout)
	encoder.SetEscapeHTML(false)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(out); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func emitRanges() {
	fmt.Println("// @generated by rust/tests/fixtures/foundation/go-quote/oracle.go -ranges; do not hand-edit.")
	fmt.Println("// Go1.26.8 / Unicode 15.0.0 strconv.IsPrint; non-ASCII inclusive scalar ranges.")
	fmt.Println("// Go-derived data: see rust/src/approval/policy/go_regex/GO-LICENSE.")
	fmt.Println("pub(super) const PRINTABLE: &[(u32, u32)] = &[")
	for r := rune(128); r <= utf8.MaxRune; r++ {
		if !strconv.IsPrint(r) {
			continue
		}
		start := r
		for r < utf8.MaxRune && strconv.IsPrint(r+1) {
			r++
		}
		fmt.Printf("    (0x%x, 0x%x),\n", start, r)
	}
	fmt.Println("];")
}
