#!/usr/bin/env python3
"""Generate Rust DTOs and reviewable schema from the fixed Go wire oracle.

This intentionally accepts only the simple tagged structs in messages.go and fails
on any unparsed field. Re-run, then run the Go golden oracle and Rust contracts.
"""
import hashlib, json, pathlib, re
ROOT=pathlib.Path(__file__).resolve().parents[2]
source=ROOT/'internal/proto/messages.go'
raw=source.read_text()
structs=[]
for m in re.finditer(r'^type (\w+) struct \{\n(.*?)^\}',raw,re.M|re.S):
    fields=[]
    for line in m[2].splitlines():
        line=line.strip()
        if not line or line.startswith('//'): continue
        f=re.fullmatch(r'(\w+)\s+(\S+)\s+`json:"([^"]+)"`(?:\s*//.*)?',line)
        if not f: raise SystemExit('Unparsed field: '+line)
        tag=f[3].split(',');fields.append({'go_name':f[1],'go_type':f[2],'wire_name':tag[0],'omitempty':'omitempty' in tag[1:]})
    structs.append({'name':m[1],'fields':fields})
aliases=re.findall(r'^type (\w+) string$',raw,re.M)
scalars={'string':'String','int':'i64','int64':'i64','uint64':'u64','bool':'bool','float64':'f64','byte':'u8'}
def typ(g,omit=True):
    if g.startswith('*'): return 'Option<'+typ(g[1:])+'>'
    if g.startswith('[]'):
        v='Vec<'+typ(g[2:])+'>'
        return v if omit else 'Option<'+v+'>'
    if g.startswith('map[string]'): return 'BTreeMap<String, '+typ(g[11:])+'>'
    if g in aliases:return 'String'
    if g in scalars:return scalars[g]
    if g in [x['name'] for x in structs]:return g
    raise SystemExit('Unsupported type: '+g)
out=['// Generated by scripts/generate-proto.py from the fixed Go wire oracle.','// Do not hand-edit; no field may be removed without the contract changing.','use serde::{Deserialize, Serialize};','use std::collections::BTreeMap;','use super::{null_default, is_zero, is_false};','']
for a in aliases:out.append('pub type '+a+' = String;')
for st in structs:
    out += ['','#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]','#[serde(default)]','pub struct '+st['name']+' {']
    for f in st['fields']:
        g=f['go_type'];name=f['wire_name'];rustname='r#'+name if name in ['type','ref','mod','loop','match','in','move','self','use'] else name
        attr=['rename = '+json.dumps(name)]
        if g=='[]byte':attr+=['with = "super::base64_bytes"']
        elif not g.startswith('*') and not (g.startswith('[]') and not f['omitempty']):attr+=['deserialize_with = "null_default"']
        if f['omitempty']:
            pred='Option::is_none' if g.startswith('*') else 'Vec::is_empty' if g.startswith('[]') else 'BTreeMap::is_empty' if g.startswith('map[') else 'String::is_empty' if g=='string' or g in aliases else 'is_false' if g=='bool' else 'is_zero' if g in scalars else None
            if pred:attr+=['skip_serializing_if = '+json.dumps(pred)]
        out+=['    #[serde('+', '.join(attr)+')]','    pub '+rustname+': '+typ(g,f['omitempty'])+',']
    out+=['}']
(ROOT/'rust/src/proto/generated.rs').write_text('\n'.join(out)+'\n')
inv={'schema_version':1,'baseline':'21d0bc7935a2c4696fb89ccff2e324157a528c2d','source':'internal/proto/messages.go','source_sha256':hashlib.sha256(raw.encode()).hexdigest(),'structs':structs,'string_aliases':aliases}
(ROOT/'rust/inventory/protocol.json').write_text(json.dumps(inv,indent=2)+'\n')
# Emit a Go fixture driver in the module, never modifying the oracle itself.
go='''// Synthetic Go encoding/json oracle. Run from the repository root.
package main
import ("encoding/json"; "fmt"; "os"; "reflect"; "many-ai-cli/internal/proto")
type Case struct { Name string `json:"name"`; Type string `json:"type"`; Value any `json:"value"` }
func fill(v reflect.Value) {
 switch v.Kind() {
 case reflect.String: v.SetString("synthetic-日本語-<&>\\u2028")
 case reflect.Bool: v.SetBool(true)
 case reflect.Int,reflect.Int64: v.SetInt(17)
 case reflect.Uint64: v.SetUint(23)
 case reflect.Float64: v.SetFloat(1.25)
 case reflect.Pointer: v.Set(reflect.New(v.Type().Elem()));fill(v.Elem())
 case reflect.Slice: v.Set(reflect.MakeSlice(v.Type(),1,1));fill(v.Index(0))
 case reflect.Uint8: v.SetUint(255)
 case reflect.Map: v.Set(reflect.MakeMap(v.Type()));k:=reflect.New(v.Type().Key()).Elem();k.SetString("synthetic");x:=reflect.New(v.Type().Elem()).Elem();fill(x);v.SetMapIndex(k,x)
 case reflect.Struct:for i:=0;i<v.NumField();i++ {fill(v.Field(i))}
 default: panic(v.Kind())
 }
}
func main(){
 values:=[]any{'''+','.join('proto.'+s['name']+'{}' for s in structs)+'''}
 cases:=[]Case{}
 for _,zero:=range values {name:=reflect.TypeOf(zero).Name();cases=append(cases,Case{name+"/zero",name,zero}); v:=reflect.New(reflect.TypeOf(zero)).Elem();fill(v);cases=append(cases,Case{name+"/filled",name,v.Interface()})}
 enc:=json.NewEncoder(os.Stdout);enc.SetIndent("","  ");if err:=enc.Encode(cases);err!=nil{fmt.Fprintln(os.Stderr,err);os.Exit(1)}
}
'''
(ROOT/'rust/tests/oracle/main.go').write_text(go)
# Compile-time exhaustive Rust dispatch ensures every schema type is tested.
test='''use many_ai_cli::proto::*;
use serde_json::Value;
#[test]
fn all_go_dto_goldens_roundtrip() {
 let cases:Vec<Value>=serde_json::from_str(include_str!("fixtures/foundation/proto-golden.json")).unwrap();
 assert_eq!(cases.len(), '''+str(len(structs)*2)+''');
 for case in cases { let v=case["value"].clone(); let actual=match case["type"].as_str().unwrap() {
'''
for st in structs:test+=' "'+st['name']+'" => serde_json::to_value(serde_json::from_value::<'+st['name']+'>(v.clone()).unwrap()).unwrap(),\n'
test+=''' _=>panic!("unknown fixture type"),
 };assert_eq!(actual,v,"{}",case["name"]); }
}
'''
(ROOT/'rust/tests/proto_golden.rs').write_text(test)
print(f'Generated {len(structs)} structs, {sum(len(s["fields"]) for s in structs)} fields')
