// Generated by scripts/generate-proto.py from the fixed Go wire oracle.
// Do not hand-edit; no field may be removed without the contract changing.
use super::{is_false, is_zero, null_default};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

pub type ApprovalRiskTier = String;

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct Message {
    #[serde(rename = "type", deserialize_with = "null_default")]
    pub r#type: String,
    #[serde(
        rename = "role",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub role: String,
    #[serde(
        rename = "session_id",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub session_id: i64,
    #[serde(
        rename = "provider",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub provider: String,
    #[serde(
        rename = "provider_revision",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub provider_revision: String,
    #[serde(
        rename = "display_name",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub display_name: String,
    #[serde(
        rename = "cwd",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub cwd: String,
    #[serde(
        rename = "branch",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub branch: String,
    #[serde(
        rename = "project_id",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub project_id: String,
    #[serde(
        rename = "pid",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub pid: i64,
    #[serde(
        rename = "input_seq",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub input_seq: i64,
    #[serde(
        rename = "input_seq_high_watermark",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub input_seq_high_watermark: i64,
    #[serde(
        rename = "shell",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub shell: String,
    #[serde(
        rename = "version",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub version: String,
    #[serde(
        rename = "state",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub state: String,
    #[serde(
        rename = "output_idle",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub output_idle: bool,
    #[serde(
        rename = "workflow_active",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub workflow_active: bool,
    #[serde(
        rename = "awaiting_user",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub awaiting_user: bool,
    #[serde(
        rename = "awaiting_approval",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub awaiting_approval: bool,
    #[serde(rename = "activity", skip_serializing_if = "Option::is_none")]
    pub activity: Option<SessionActivity>,
    #[serde(rename = "workflow_progress", skip_serializing_if = "Option::is_none")]
    pub workflow_progress: Option<WorkflowProgress>,
    #[serde(rename = "subagent_tree", skip_serializing_if = "Option::is_none")]
    pub subagent_tree: Option<SubagentTree>,
    #[serde(
        rename = "exit_code",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub exit_code: i64,
    #[serde(
        rename = "signal",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub signal: String,
    #[serde(
        rename = "token",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub token: String,
    #[serde(
        rename = "home_dir",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub home_dir: String,
    #[serde(
        rename = "codex_home",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub codex_home: String,
    #[serde(
        rename = "claude_dir",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub claude_dir: String,
    #[serde(
        rename = "grok_home",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub grok_home: String,
    #[serde(
        rename = "agent_session_id",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub agent_session_id: String,
    #[serde(
        rename = "subscription_id",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub subscription_id: String,
    #[serde(
        rename = "subscription_name",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub subscription_name: String,
    #[serde(
        rename = "usage_probe",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub usage_probe: bool,
    #[serde(
        rename = "subscription_login",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub subscription_login: bool,
    #[serde(
        rename = "data",
        with = "super::base64_bytes",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub data: Vec<u8>,
    #[serde(
        rename = "text",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub text: String,
    #[serde(
        rename = "messages",
        deserialize_with = "null_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub messages: Vec<AgentChatMessage>,
    #[serde(
        rename = "cols",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub cols: i64,
    #[serde(
        rename = "rows",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub rows: i64,
    #[serde(
        rename = "log_path",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub log_path: String,
    #[serde(
        rename = "jsonl_path",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub jsonl_path: String,
    #[serde(
        rename = "replay_b64",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub replay_b64: String,
    #[serde(
        rename = "reason",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub reason: String,
    #[serde(
        rename = "pty_bytes",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub pty_bytes: i64,
    #[serde(
        rename = "replay",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub replay: bool,
    #[serde(
        rename = "replay_epoch",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub replay_epoch: u64,
    #[serde(
        rename = "approval_source_epoch",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub approval_source_epoch: u64,
    #[serde(rename = "token_statusbar", deserialize_with = "null_default")]
    pub token_statusbar: bool,
    #[serde(
        rename = "approval_sig",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub approval_sig: String,
    #[serde(
        rename = "approval_source",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub approval_source: String,
    #[serde(rename = "approval_summary", skip_serializing_if = "Option::is_none")]
    pub approval_summary: Option<ApprovalSummary>,
    #[serde(
        rename = "approval_candidate_key",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub approval_candidate_key: String,
    #[serde(
        rename = "approval_candidate_shape",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub approval_candidate_shape: String,
    #[serde(
        rename = "approval_consumed",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub approval_consumed: bool,
    #[serde(
        rename = "approval_consumed_epoch",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub approval_consumed_epoch: u64,
    #[serde(rename = "done_summary", skip_serializing_if = "Option::is_none")]
    pub done_summary: Option<DoneSummary>,
    #[serde(
        rename = "sent_text",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub sent_text: String,
    #[serde(
        rename = "detected_at",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub detected_at: String,
    #[serde(rename = "approval_state", skip_serializing_if = "Option::is_none")]
    pub approval_state: Option<ApprovalState>,
    #[serde(
        rename = "approval_snapshot",
        deserialize_with = "null_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub approval_snapshot: Vec<ApprovalSessionState>,
    #[serde(
        rename = "last_output_at",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub last_output_at: String,
    #[serde(
        rename = "transcript_grew_at",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub transcript_grew_at: String,
    #[serde(
        rename = "started_at",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub started_at: String,
    #[serde(
        rename = "label",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub label: String,
    #[serde(
        rename = "launch_label",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub launch_label: String,
    #[serde(rename = "session_meta", skip_serializing_if = "Option::is_none")]
    pub session_meta: Option<SessionMeta>,
    #[serde(
        rename = "model",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub model: String,
    #[serde(
        rename = "effort",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub effort: String,
    #[serde(
        rename = "execution_mode",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub execution_mode: String,
    #[serde(
        rename = "permission_preset",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub permission_preset: String,
    #[serde(
        rename = "permission_mode",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub permission_mode: String,
    #[serde(
        rename = "route",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub route: String,
    #[serde(
        rename = "parent_session_id",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub parent_session_id: i64,
    #[serde(
        rename = "handoff_from",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub handoff_from: i64,
    #[serde(
        rename = "auto",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub auto: bool,
    #[serde(
        rename = "depth",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub depth: i64,
    #[serde(
        rename = "orchestration_id",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub orchestration_id: String,
    #[serde(
        rename = "board_path",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub board_path: String,
    #[serde(
        rename = "worktree_branch",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub worktree_branch: String,
    #[serde(
        rename = "board_notify_pending",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub board_notify_pending: bool,
    #[serde(
        rename = "relays",
        deserialize_with = "null_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub relays: Vec<RelayStatus>,
    #[serde(
        rename = "cross_session_messages",
        deserialize_with = "null_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub cross_session_messages: Vec<CrossSessionMessage>,
    #[serde(
        rename = "spawn_confirmation_id",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub spawn_confirmation_id: String,
    #[serde(
        rename = "initial_prompt",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub initial_prompt: String,
    #[serde(
        rename = "spawn_requested_at_ms",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub spawn_requested_at_ms: i64,
    #[serde(
        rename = "remember_permission",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub remember_permission: bool,
    #[serde(
        rename = "spawn_child_approval",
        deserialize_with = "null_default",
        skip_serializing_if = "BTreeMap::is_empty"
    )]
    pub spawn_child_approval: BTreeMap<String, BTreeMap<String, ChildApproval>>,
    #[serde(
        rename = "trust_grant_providers",
        deserialize_with = "null_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub trust_grant_providers: Vec<String>,
    #[serde(
        rename = "spawn_child_session_id",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub spawn_child_session_id: i64,
    #[serde(
        rename = "first_message",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub first_message: String,
    #[serde(
        rename = "last_message",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub last_message: String,
    #[serde(
        rename = "inject",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub inject: String,
    #[serde(
        rename = "image_data",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub image_data: String,
    #[serde(
        rename = "filename",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub filename: String,
    #[serde(
        rename = "providers",
        deserialize_with = "null_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub providers: Vec<String>,
    #[serde(
        rename = "ui_active_session_id",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub ui_active_session_id: i64,
    #[serde(
        rename = "git_checked",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub git_checked: bool,
    #[serde(
        rename = "git_files",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub git_files: i64,
    #[serde(
        rename = "git_added",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub git_added: i64,
    #[serde(
        rename = "git_deleted",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub git_deleted: i64,
    #[serde(
        rename = "commit_subject",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub commit_subject: String,
    #[serde(
        rename = "commit_body",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub commit_body: String,
    #[serde(
        rename = "cost_usd",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub cost_usd: f64,
    #[serde(
        rename = "cost_known",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub cost_known: bool,
    #[serde(
        rename = "tokens_in",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub tokens_in: i64,
    #[serde(
        rename = "tokens_out",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub tokens_out: i64,
    #[serde(
        rename = "tokens_cache",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub tokens_cache: i64,
    #[serde(
        rename = "tokens_total",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub tokens_total: i64,
    #[serde(
        rename = "ctx_window",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub ctx_window: i64,
    #[serde(
        rename = "ctx_used_pct",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub ctx_used_pct: f64,
    #[serde(
        rename = "usage_model",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub usage_model: String,
    #[serde(
        rename = "usage_started_at",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub usage_started_at: String,
    #[serde(
        rename = "rl_5h_pct",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub rl_5h_pct: f64,
    #[serde(
        rename = "rl_5h_reset",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub rl_5h_reset: i64,
    #[serde(
        rename = "rl_7d_pct",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub rl_7d_pct: f64,
    #[serde(
        rename = "rl_7d_reset",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub rl_7d_reset: i64,
    #[serde(
        rename = "claude_rate_limits_present",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub claude_rate_limits_present: bool,
    #[serde(
        rename = "claude_5h_field_present",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub claude_5h_field_present: bool,
    #[serde(
        rename = "claude_5h_present",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub claude_5h_present: bool,
    #[serde(
        rename = "claude_7d_field_present",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub claude_7d_field_present: bool,
    #[serde(
        rename = "claude_7d_present",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub claude_7d_present: bool,
    #[serde(
        rename = "codex_rate_limits_present",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub codex_rate_limits_present: bool,
    #[serde(
        rename = "codex_primary_present",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub codex_primary_present: bool,
    #[serde(
        rename = "codex_primary_used_pct",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub codex_primary_used_pct: f64,
    #[serde(
        rename = "codex_primary_window_minutes",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub codex_primary_window_minutes: i64,
    #[serde(
        rename = "codex_primary_reset",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub codex_primary_reset: i64,
    #[serde(
        rename = "codex_secondary_used_pct",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub codex_secondary_used_pct: f64,
    #[serde(
        rename = "codex_secondary_present",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub codex_secondary_present: bool,
    #[serde(
        rename = "codex_secondary_window_minutes",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub codex_secondary_window_minutes: i64,
    #[serde(
        rename = "codex_secondary_reset",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub codex_secondary_reset: i64,
    #[serde(
        rename = "codex_credits_present",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub codex_credits_present: bool,
    #[serde(
        rename = "codex_has_credits",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub codex_has_credits: bool,
    #[serde(
        rename = "codex_credits_unlimited",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub codex_credits_unlimited: bool,
    #[serde(
        rename = "codex_credits_balance",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub codex_credits_balance: String,
    #[serde(
        rename = "codex_plan_type",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub codex_plan_type: String,
    #[serde(
        rename = "usage_observed_at",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub usage_observed_at: String,
    #[serde(
        rename = "lines_added",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub lines_added: i64,
    #[serde(
        rename = "lines_removed",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub lines_removed: i64,
    #[serde(
        rename = "effort_level",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub effort_level: String,
    #[serde(
        rename = "thinking",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub thinking: bool,
    #[serde(
        rename = "exceeds_200k",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub exceeds_200k: bool,
    #[serde(
        rename = "duration_ms",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub duration_ms: i64,
    #[serde(
        rename = "api_duration_ms",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub api_duration_ms: i64,
    #[serde(
        rename = "output_style",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub output_style: String,
    #[serde(
        rename = "vim_mode",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub vim_mode: String,
    #[serde(
        rename = "agent_name",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub agent_name: String,
    #[serde(
        rename = "repo_host",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub repo_host: String,
    #[serde(
        rename = "repo_owner",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub repo_owner: String,
    #[serde(
        rename = "repo_name",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub repo_name: String,
    #[serde(
        rename = "remaining_pct",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub remaining_pct: f64,
    #[serde(
        rename = "reasoning_output_tokens",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub reasoning_output_tokens: i64,
    #[serde(
        rename = "note_ok",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub note_ok: bool,
    #[serde(
        rename = "note_path",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub note_path: String,
    #[serde(rename = "binary_stale", skip_serializing_if = "Option::is_none")]
    pub binary_stale: Option<bool>,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct CrossSessionMessage {
    #[serde(
        rename = "at",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub at: String,
    #[serde(
        rename = "receiver_session_id",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub receiver_session_id: i64,
    #[serde(
        rename = "receiver_role",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub receiver_role: String,
    #[serde(
        rename = "sender",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub sender: String,
    #[serde(
        rename = "text",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub text: String,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct AgentChatMessage {
    #[serde(rename = "role", deserialize_with = "null_default")]
    pub role: String,
    #[serde(
        rename = "kind",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub kind: String,
    #[serde(
        rename = "text",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub text: String,
    #[serde(
        rename = "thinking",
        deserialize_with = "null_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub thinking: Vec<String>,
    #[serde(
        rename = "tools",
        deserialize_with = "null_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub tools: Vec<AgentChatTool>,
    #[serde(
        rename = "ts",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub ts: String,
    #[serde(
        rename = "message_id",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub message_id: String,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct AgentChatTool {
    #[serde(
        rename = "id",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub id: String,
    #[serde(rename = "name", deserialize_with = "null_default")]
    pub name: String,
    #[serde(
        rename = "input",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub input: String,
    #[serde(
        rename = "result",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub result: String,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SessionActivity {
    #[serde(rename = "output_idle", deserialize_with = "null_default")]
    pub output_idle: bool,
    #[serde(rename = "workflow_active", deserialize_with = "null_default")]
    pub workflow_active: bool,
    #[serde(rename = "awaiting_user", deserialize_with = "null_default")]
    pub awaiting_user: bool,
    #[serde(rename = "awaiting_approval", deserialize_with = "null_default")]
    pub awaiting_approval: bool,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct WorkflowProgress {
    #[serde(rename = "detected", deserialize_with = "null_default")]
    pub detected: bool,
    #[serde(
        rename = "source",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub source: String,
    #[serde(
        rename = "name",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub name: String,
    #[serde(rename = "done", deserialize_with = "null_default")]
    pub done: i64,
    #[serde(rename = "total", deserialize_with = "null_default")]
    pub total: i64,
    #[serde(rename = "running", deserialize_with = "null_default")]
    pub running: i64,
    #[serde(rename = "failed", deserialize_with = "null_default")]
    pub failed: i64,
    #[serde(rename = "pending", deserialize_with = "null_default")]
    pub pending: i64,
    #[serde(rename = "waiting_dynamic", deserialize_with = "null_default")]
    pub waiting_dynamic: i64,
    #[serde(rename = "percent", deserialize_with = "null_default")]
    pub percent: i64,
    #[serde(
        rename = "elapsed_sec",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub elapsed_sec: i64,
    #[serde(
        rename = "tokens_raw",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub tokens_raw: String,
    #[serde(
        rename = "phases",
        deserialize_with = "null_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub phases: Vec<WfPhase>,
    #[serde(rename = "settled", deserialize_with = "null_default")]
    pub settled: bool,
    #[serde(
        rename = "settled_by",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub settled_by: String,
    #[serde(
        rename = "task_detail_source",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub task_detail_source: String,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct WfPhase {
    #[serde(rename = "title", deserialize_with = "null_default")]
    pub title: String,
    #[serde(rename = "agents")]
    pub agents: Option<Vec<WfAgent>>,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct WfAgent {
    #[serde(rename = "label", deserialize_with = "null_default")]
    pub label: String,
    #[serde(rename = "state", deserialize_with = "null_default")]
    pub state: String,
    #[serde(
        rename = "metrics",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub metrics: String,
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<WfAgentDetail>,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct WfAgentDetail {
    #[serde(
        rename = "model",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub model: String,
    #[serde(
        rename = "started_at",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub started_at: i64,
    #[serde(
        rename = "last_progress_at",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub last_progress_at: i64,
    #[serde(
        rename = "duration_ms",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub duration_ms: i64,
    #[serde(
        rename = "tokens",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub tokens: i64,
    #[serde(
        rename = "tool_calls",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub tool_calls: i64,
    #[serde(
        rename = "last_tool_name",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub last_tool_name: String,
    #[serde(
        rename = "last_tool_summary",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub last_tool_summary: String,
    #[serde(
        rename = "prompt_preview",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub prompt_preview: String,
    #[serde(
        rename = "result_preview",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub result_preview: String,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SubagentTree {
    #[serde(
        rename = "provider",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub provider: String,
    #[serde(
        rename = "nodes",
        deserialize_with = "null_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub nodes: Vec<SubagentNode>,
    #[serde(
        rename = "omitted",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub omitted: i64,
    #[serde(
        rename = "updated_at",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub updated_at: i64,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SubagentNode {
    #[serde(rename = "id", deserialize_with = "null_default")]
    pub id: String,
    #[serde(
        rename = "parent_id",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub parent_id: String,
    #[serde(rename = "depth", deserialize_with = "null_default")]
    pub depth: i64,
    #[serde(
        rename = "label",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub label: String,
    #[serde(
        rename = "agent_type",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub agent_type: String,
    #[serde(
        rename = "model",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub model: String,
    #[serde(rename = "state", deserialize_with = "null_default")]
    pub state: String,
    #[serde(
        rename = "started_at",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub started_at: i64,
    #[serde(
        rename = "last_activity_at",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub last_activity_at: i64,
    #[serde(
        rename = "finished_at",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub finished_at: i64,
    #[serde(
        rename = "tool_calls",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub tool_calls: i64,
    #[serde(
        rename = "last_tool_name",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub last_tool_name: String,
    #[serde(
        rename = "last_tool_summary",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub last_tool_summary: String,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SessionMeta {
    #[serde(rename = "label", deserialize_with = "null_default")]
    pub label: String,
    #[serde(rename = "pinned", deserialize_with = "null_default")]
    pub pinned: bool,
    #[serde(rename = "color", deserialize_with = "null_default")]
    pub color: String,
    #[serde(rename = "note", deserialize_with = "null_default")]
    pub note: String,
    #[serde(rename = "auto_title", deserialize_with = "null_default")]
    pub auto_title: String,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ApprovalSummary {
    #[serde(
        rename = "command",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub command: String,
    #[serde(
        rename = "paths",
        deserialize_with = "null_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub paths: Vec<String>,
    #[serde(rename = "risk", deserialize_with = "null_default")]
    pub risk: String,
    #[serde(
        rename = "raw",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub raw: String,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct DoneSummary {
    #[serde(rename = "session_id", deserialize_with = "null_default")]
    pub session_id: i64,
    #[serde(
        rename = "provider",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub provider: String,
    #[serde(
        rename = "title",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub title: String,
    #[serde(rename = "text", deserialize_with = "null_default")]
    pub text: String,
    #[serde(rename = "kind", deserialize_with = "null_default")]
    pub kind: String,
    #[serde(rename = "at", deserialize_with = "null_default")]
    pub at: String,
    #[serde(
        rename = "fallback",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub fallback: bool,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct RelayStatus {
    #[serde(
        rename = "orchestration_id",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub orchestration_id: String,
    #[serde(
        rename = "plan_path",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub plan_path: String,
    #[serde(
        rename = "mode",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub mode: String,
    #[serde(
        rename = "state",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub state: String,
    #[serde(
        rename = "reason",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub reason: String,
    #[serde(
        rename = "completed_cs",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub completed_cs: i64,
    #[serde(
        rename = "round",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub round: i64,
    #[serde(
        rename = "max_rounds",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub max_rounds: i64,
    #[serde(
        rename = "final_seen",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub final_seen: bool,
    #[serde(
        rename = "implementation_session_id",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub implementation_session_id: i64,
    #[serde(
        rename = "strong_session_id",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub strong_session_id: i64,
    #[serde(
        rename = "active_implementer",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub active_implementer: String,
    #[serde(
        rename = "escalate_after",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub escalate_after: i64,
    #[serde(
        rename = "review_session_id",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub review_session_id: i64,
    #[serde(
        rename = "review_path",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub review_path: String,
    #[serde(
        rename = "worktree_path",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub worktree_path: String,
    #[serde(
        rename = "branch",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub branch: String,
    #[serde(
        rename = "base_commit",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub base_commit: String,
    #[serde(
        rename = "updated_at",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub updated_at: String,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct RelayEvent {
    #[serde(
        rename = "at",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub at: String,
    #[serde(
        rename = "kind",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub kind: String,
    #[serde(
        rename = "c",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub c: i64,
    #[serde(
        rename = "round",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub round: i64,
    #[serde(
        rename = "text",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub text: String,
    #[serde(
        rename = "review_path",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub review_path: String,
    #[serde(
        rename = "commit",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub commit: String,
    #[serde(
        rename = "files_changed",
        deserialize_with = "null_default",
        skip_serializing_if = "is_zero"
    )]
    pub files_changed: i64,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ApprovalOption {
    #[serde(rename = "num", deserialize_with = "null_default")]
    pub num: i64,
    #[serde(
        rename = "label",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub label: String,
    #[serde(
        rename = "is_current",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub is_current: bool,
    #[serde(
        rename = "send_text",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub send_text: String,
    #[serde(
        rename = "preserve_order",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub preserve_order: bool,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ApprovalRecord {
    #[serde(rename = "candidate_key", deserialize_with = "null_default")]
    pub candidate_key: String,
    #[serde(
        rename = "candidate_shape",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub candidate_shape: String,
    #[serde(rename = "source_epoch", deserialize_with = "null_default")]
    pub source_epoch: u64,
    #[serde(
        rename = "sig",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub sig: String,
    #[serde(rename = "origin", deserialize_with = "null_default")]
    pub origin: String,
    #[serde(
        rename = "source",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub source: String,
    #[serde(
        rename = "kind",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub kind: String,
    #[serde(
        rename = "block",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub block: String,
    #[serde(
        rename = "question",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub question: String,
    #[serde(
        rename = "context",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub context: String,
    #[serde(
        rename = "options",
        deserialize_with = "null_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub options: Vec<ApprovalOption>,
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<ApprovalSummary>,
    #[serde(
        rename = "detected_at",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub detected_at: String,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ApprovalRecordClose {
    #[serde(rename = "candidate_key", deserialize_with = "null_default")]
    pub candidate_key: String,
    #[serde(rename = "source_epoch", deserialize_with = "null_default")]
    pub source_epoch: u64,
    #[serde(
        rename = "sig",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub sig: String,
    #[serde(
        rename = "origin",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub origin: String,
    #[serde(rename = "reason", deserialize_with = "null_default")]
    pub reason: String,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ApprovalState {
    #[serde(rename = "version", deserialize_with = "null_default")]
    pub version: u64,
    #[serde(rename = "open", skip_serializing_if = "Option::is_none")]
    pub open: Option<ApprovalRecord>,
    #[serde(rename = "close", skip_serializing_if = "Option::is_none")]
    pub close: Option<ApprovalRecordClose>,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ApprovalSessionState {
    #[serde(rename = "session_id", deserialize_with = "null_default")]
    pub session_id: i64,
    #[serde(rename = "version", deserialize_with = "null_default")]
    pub version: u64,
    #[serde(rename = "record", skip_serializing_if = "Option::is_none")]
    pub record: Option<ApprovalRecord>,
}

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ChildApproval {
    #[serde(
        rename = "permission_mode",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub permission_mode: String,
    #[serde(
        rename = "sandbox",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub sandbox: String,
    #[serde(
        rename = "ask_for_approval",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub ask_for_approval: String,
    #[serde(
        rename = "allowed_tools",
        deserialize_with = "null_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub allowed_tools: Vec<String>,
    #[serde(
        rename = "risk_confirmed",
        deserialize_with = "null_default",
        skip_serializing_if = "is_false"
    )]
    pub risk_confirmed: bool,
    #[serde(
        rename = "tier",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub tier: String,
    #[serde(
        rename = "fallback_from",
        deserialize_with = "null_default",
        skip_serializing_if = "String::is_empty"
    )]
    pub fallback_from: String,
}
