param(
  [string]$OutputPath = "THIRD_PARTY_NOTICES.md"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\.." )).Path
Push-Location $repoRoot
try {
  $moduleLines = go list -m all
  if (-not $moduleLines) {
    throw "go list -m all returned no modules"
  }

  $rows = New-Object System.Collections.Generic.List[string]
  $details = New-Object System.Collections.Generic.List[object]
  $rows.Add("# Third-Party Notices")
  $rows.Add("")
  $rows.Add("This file is auto-generated by `scripts/local/gen-third-party-notices.ps1`.")
  $rows.Add("")
  $rows.Add("| Module | Version | License File |")
  $rows.Add("|---|---|---|")

  foreach ($line in $moduleLines) {
    $trimmed = $line.Trim()
    if ([string]::IsNullOrWhiteSpace($trimmed)) { continue }

    $parts = $trimmed -split "\s+"
    if ($parts.Length -lt 2) { continue }

    $module = $parts[0]
    $version = $parts[1]

    $licenseLabel = "(not found)"
    $licenseFiles = @()
    $json = go mod download -json "$module@$version" 2>$null
    if ($LASTEXITCODE -eq 0 -and $json) {
      $info = $json | ConvertFrom-Json
      if ($info.Dir) {
        $patterns = @("LICENSE*", "COPYING*", "NOTICE*")
        foreach ($pattern in $patterns) {
          $matches = Get-ChildItem -LiteralPath $info.Dir -File -Filter $pattern -ErrorAction SilentlyContinue
          foreach ($match in $matches) {
            $knownPaths = @($licenseFiles | ForEach-Object { $_.FullName })
            if ($knownPaths -notcontains $match.FullName) {
              $licenseFiles += $match
            }
          }
        }
        if ($licenseFiles.Count -gt 0) {
          $licenseLabel = ($licenseFiles | ForEach-Object { $_.Name }) -join ", "
        }
      }
    }

    $rows.Add("| $module | $version | $licenseLabel |")
    if ($licenseFiles.Count -gt 0) {
      $details.Add([pscustomobject]@{
        Module = $module
        Version = $version
        Files = $licenseFiles
      })
    }
  }

  if ($details.Count -gt 0) {
    $rows.Add("")
    $rows.Add("## License Texts")
    foreach ($entry in $details) {
      $rows.Add("")
      $rows.Add("### $($entry.Module) $($entry.Version)")
      foreach ($file in $entry.Files) {
        $rows.Add("")
        $rows.Add("#### $($file.Name)")
        $rows.Add("")
        $rows.Add("````text")
        $content = Get-Content -LiteralPath $file.FullName -Raw
        $rows.Add($content.TrimEnd())
        $rows.Add("````")
      }
    }
  }

  $resolvedOutputPath = if ([System.IO.Path]::IsPathRooted($OutputPath)) { $OutputPath } else { Join-Path $repoRoot $OutputPath }
  [System.IO.File]::WriteAllLines($resolvedOutputPath, $rows)
  Write-Host "Generated $OutputPath"
}
finally {
  Pop-Location
}
