#!/usr/bin/env python3
"""Run commit-pinned preference handlers with owned config files and fake push state."""
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[4]
SHA = '21d0bc7935a2c4696fb89ccff2e324157a528c2d'
GO = os.environ['GO']  # Caller supplies the pinned Go executable; no machine paths.
if 'go1.26.8 ' not in subprocess.check_output([GO, 'version'], text=True):
    raise SystemExit('oracle requires pinned Go 1.26.8')
sources = {}
def source(path):
    if path not in sources:
        data = subprocess.check_output(['git', 'show', f'{SHA}:{path}'], cwd=ROOT)
        if (ROOT / path).read_bytes().replace(b'\r\n', b'\n') != data.replace(b'\r\n', b'\n'):
            raise SystemExit(f'pinned source differs: {path}')
        sources[path] = data.decode()
    return sources[path]
def decl(path, marker):
    text = source(path)
    start = text.index(marker)
    return text[start:text.index('\n}', start)+2] + '\n'
# The observer imports the real config package and private persistence helpers.
for directory in ['internal/config', 'internal/securefile', 'internal/wslutil']:
    for path in sorted((ROOT/directory).glob('*.go')):
        if not path.name.endswith('_test.go'):
            source(path.relative_to(ROOT).as_posix())
parts = []
for name in ['notifySoundCustomPath', 'avatarUploadPath', '(s *Server) handleUserPrefs(', '(s *Server) handleUserPrefsGet', 'userPrefsTemplateVersion', 'sanitizeAvatarPref', '(s *Server) handleUserPrefsPut', 'sanitizeNotifySoundPref', 'notifySoundAllowed']:
    parts.append(decl('internal/hub/user_prefs_handlers.go', 'func '+name))
for name in ['(s *Server) doneSummaryNotifyEnabled', '(s *Server) hasPushSubscription']:
    parts.append(decl('internal/hub/done_summary.go', 'func '+name))
parts.append(decl('internal/hub/misc_handlers.go', 'func pathExistsCandidateKey'))
for name in ['requireMethodOneOf', 'decodeJSON', 'writeJSON(', 'writeJSONStatus', 'writeJSONError', 'errorDetail']:
    parts.append(decl('internal/hub/http_helpers.go', 'func '+name))
parts.append(decl('internal/hub/http_helpers.go', 'type httpErrorResp struct'))
header = '''//go:build ignore

// Pinned handler extraction generated by generate.py. Synthetic observer only.
package main
import (
 "crypto/sha256"; "encoding/hex"; "encoding/json"; "fmt"; "io"; "log/slog";
 "net/http"; "net/http/httptest"; "os"; "path/filepath"; "regexp"; "runtime"; "strings"; "sync";
 "many-ai-cli/internal/config"; "gopkg.in/yaml.v3"
)
const jsonBodyMaxBytes = 1024 * 1024
type pushManager struct { count int }
func (p *pushManager) status() struct{Subscriptions int} { return struct{Subscriptions int}{p.count} }
type Server struct { cfg *config.Config; cfgMu sync.Mutex; logger *slog.Logger; push *pushManager }
func (s *Server) guard(w http.ResponseWriter,r *http.Request,methods ...string) bool { return requireMethodOneOf(w,r,methods...) }
func must(e error) { if e != nil { panic(e) } }
'''
(HERE/'oracle.go').write_text(header + '\n'.join(parts) + (HERE/'harness.go.txt').read_text())
with tempfile.TemporaryDirectory(prefix='user-preferences-observer-') as temporary:
    env = dict(os.environ, GOMODCACHE=os.environ['GOMODCACHE'], GOCACHE=os.environ['GOCACHE'], HOME=temporary, USERPROFILE=temporary, GOTOOLCHAIN='local', GOPROXY='off', GOSUMDB='off', GOTELEMETRY='off', GOENV='off', TZ='UTC')
    run = subprocess.run([GO, 'run', str(HERE/'oracle.go'), str(HERE/'cases.json')], cwd=ROOT, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    sys.stderr.buffer.write(run.stderr)
    if run.returncode:
        raise SystemExit(run.returncode)
    result = {'baseline': SHA, 'source_sha256': {p: hashlib.sha256(s.encode()).hexdigest() for p,s in sorted(sources.items())}, 'cases': json.loads(run.stdout)}
    Path(sys.argv[1]).write_text(json.dumps(result, ensure_ascii=True, indent=2)+'\n')
