//go:build ignore

// Pinned handler extraction generated by generate.py. Synthetic observer only.
package main
import (
 "crypto/sha256"; "encoding/hex"; "encoding/json"; "fmt"; "io"; "log/slog";
 "net/http"; "net/http/httptest"; "os"; "path/filepath"; "regexp"; "runtime"; "strings"; "sync";
 "many-ai-cli/internal/config"; "gopkg.in/yaml.v3"
)
const jsonBodyMaxBytes = 1024 * 1024
type pushManager struct { count int }
func (p *pushManager) status() struct{Subscriptions int} { return struct{Subscriptions int}{p.count} }
type Server struct { cfg *config.Config; cfgMu sync.Mutex; logger *slog.Logger; push *pushManager }
func (s *Server) guard(w http.ResponseWriter,r *http.Request,methods ...string) bool { return requireMethodOneOf(w,r,methods...) }
func must(e error) { if e != nil { panic(e) } }
func notifySoundCustomPath() (string, error) {
	dir, err := config.Dir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "notify_sound_custom.bin"), nil
}

func avatarUploadPath() (string, error) {
	dir, err := config.Dir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "user_avatar.bin"), nil
}

func (s *Server) handleUserPrefs(w http.ResponseWriter, r *http.Request) {
	if !s.guard(w, r, http.MethodGet, http.MethodPut) {
		return
	}
	switch r.Method {
	case http.MethodGet:
		s.handleUserPrefsGet(w, r)
	case http.MethodPut:
		s.handleUserPrefsPut(w, r)
	}
}

func (s *Server) handleUserPrefsGet(w http.ResponseWriter, _ *http.Request) {
	s.cfgMu.Lock()
	prefs := s.cfg.UserPrefs.Clone()
	s.cfgMu.Unlock()
	// 完了サマリー通知は未設定のとき「通知チャネルがあれば ON」で動く。保存値
	// （nil）をそのまま返すと設定画面のトグルが OFF に見えるのに通知は飛ぶ、と
	// いう食い違いになるので、**実効値**を埋めてから返す。画面が嘘をつかない方を
	// 優先する。利用者がトグルを触れば、その時点で明示値が保存される。
	if prefs.DoneSummaryNotify.Enabled == nil {
		effective := s.doneSummaryNotifyEnabled()
		prefs.DoneSummaryNotify.Enabled = &effective
	}
	w.Header().Set("X-Template-Version", userPrefsTemplateVersion(prefs.Templates))
	writeJSON(w, prefs)
}

func userPrefsTemplateVersion(templates []config.UserPrefsTemplate) string {
	if templates == nil {
		templates = []config.UserPrefsTemplate{}
	}
	body, _ := json.Marshal(templates)
	digest := sha256.Sum256(body)
	return hex.EncodeToString(digest[:])
}

func sanitizeAvatarPref(avatar string) string {
	avatar = strings.TrimSpace(avatar)
	if avatar == "" {
		return ""
	}
	if strings.HasPrefix(avatar, "http://") || strings.HasPrefix(avatar, "https://") {
		return avatar
	}
	if uploadPath, err := avatarUploadPath(); err == nil && pathExistsCandidateKey(avatar) == pathExistsCandidateKey(uploadPath) {
		return avatar
	}
	return ""
}

func (s *Server) handleUserPrefsPut(w http.ResponseWriter, r *http.Request) {
	var prefs config.UserPrefs
	if !decodeJSON(w, r, &prefs) {
		return
	}
	prefs.Avatar = sanitizeAvatarPref(prefs.Avatar)
	prefs.NotifySound = sanitizeNotifySoundPref(prefs.NotifySound)
	prefs.Display.CustomThemes = config.SanitizeCustomThemes(prefs.Display.CustomThemes)
	prefs.Display.Theme = config.SanitizeDisplayTheme(prefs.Display.Theme, prefs.Display.CustomThemes)
	s.cfgMu.Lock()
	switch r.Header.Get("X-Template-Write") {
	case "preserve":
		prefs.Templates = s.cfg.UserPrefs.Clone().Templates
	case "compare":
		if r.Header.Get("X-Template-Version") != userPrefsTemplateVersion(s.cfg.UserPrefs.Templates) {
			s.cfgMu.Unlock()
			writeJSONError(w, http.StatusConflict, "template_conflict", "shared templates changed on another device")
			return
		}
	}
	// Compare/preserve, persistence, and publication form one transaction. A
	// failed save must not advance the shared-template version in memory, and
	// a second editor must not be admitted against an uncommitted version.
	// This endpoint deliberately holds cfgMu through the atomic config save;
	// its response is the exact snapshot this request committed.
	next := s.cfg.Clone()
	next.UserPrefs = prefs
	if err := config.Save(next); err != nil {
		s.cfgMu.Unlock()
		s.logger.Warn("save config failed", "err", err)
		writeJSONError(w, http.StatusInternalServerError, "save_failed", errorDetail("save failed", err))
		return
	}
	s.cfg.UserPrefs = next.UserPrefs.Clone()
	saved := next.UserPrefs.Clone()
	s.cfgMu.Unlock()
	w.Header().Set("X-Template-Version", userPrefsTemplateVersion(saved.Templates))
	writeJSON(w, saved)
}

func sanitizeNotifySoundPref(sound config.UserPrefsNotifySound) config.UserPrefsNotifySound {
	if sound.CustomFile == "" && sound.CustomMime == "" {
		return sound
	}
	path, err := notifySoundCustomPath()
	if err != nil || pathExistsCandidateKey(sound.CustomFile) != pathExistsCandidateKey(path) || !notifySoundAllowed(sound.CustomMime) {
		sound.CustomFile = ""
		sound.CustomMime = ""
		return sound
	}
	sound.CustomFile = path
	return sound
}

func notifySoundAllowed(mime string) bool {
	mime = strings.TrimSpace(strings.ToLower(mime))
	if mime == "" {
		return false
	}
	if i := strings.Index(mime, ";"); i >= 0 {
		mime = strings.TrimSpace(mime[:i])
	}
	return strings.HasPrefix(mime, "audio/")
}

func (s *Server) doneSummaryNotifyEnabled() bool {
	s.cfgMu.Lock()
	explicit := s.cfg.UserPrefs.DoneSummaryNotify.Enabled
	backends := len(s.cfg.Notify.Backends)
	s.cfgMu.Unlock()
	if explicit != nil {
		return *explicit
	}
	if backends > 0 {
		return true
	}
	return s.hasPushSubscription()
}

func (s *Server) hasPushSubscription() bool {
	if s.push == nil {
		return false
	}
	return s.push.status().Subscriptions > 0
}

func pathExistsCandidateKey(path string) string {
	key := filepath.Clean(path)
	if runtime.GOOS == "windows" {
		key = strings.ToLower(key)
	}
	return key
}

func requireMethodOneOf(w http.ResponseWriter, r *http.Request, methods ...string) bool {
	for _, method := range methods {
		if r.Method == method {
			return true
		}
	}
	writeJSONError(w, http.StatusMethodNotAllowed, "method_not_allowed", "method not allowed")
	return false
}

func decodeJSON(w http.ResponseWriter, r *http.Request, dst any) bool {
	dec := json.NewDecoder(http.MaxBytesReader(w, r.Body, jsonBodyMaxBytes))
	if err := dec.Decode(dst); err != nil {
		writeJSONError(w, http.StatusBadRequest, "bad_request", "invalid json")
		return false
	}
	return true
}

func writeJSON(w http.ResponseWriter, v any) {
	writeJSONStatus(w, http.StatusOK, v)
}

func writeJSONStatus(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	if status != http.StatusOK {
		w.WriteHeader(status)
	}
	_ = json.NewEncoder(w).Encode(v)
}

func writeJSONError(w http.ResponseWriter, status int, code, detail string) {
	if code == "" {
		code = "error"
	}
	if detail == "" {
		detail = http.StatusText(status)
	}
	writeJSONStatus(w, status, httpErrorResp{
		OK:     false,
		Error:  code,
		Detail: detail,
	})
}

func errorDetail(prefix string, err error) string {
	if err == nil {
		return prefix
	}
	if prefix == "" {
		return err.Error()
	}
	return fmt.Sprintf("%s: %v", prefix, err)
}

type httpErrorResp struct {
	OK     bool   `json:"ok"`
	Error  string `json:"error"`
	Detail string `json:"detail,omitempty"`
}
type input struct {
 Name string `json:"name"`
 Method string `json:"method"`
 Body string `json:"body"`
 Initial config.UserPrefs `json:"initial"`
 Policy string `json:"policy"`
 Version string `json:"version"`
 Backends int `json:"backends"`
 Push int `json:"push"`
 FailSave bool `json:"fail_save"`
}
func main() {
 raw,e:=os.ReadFile(os.Args[1]);must(e)
 var cases []input;must(json.Unmarshal(raw,&cases)); rows:=[]any{}
 for _,c:=range cases {
  home,e:=os.MkdirTemp("", "user-preferences-owned-");must(e)
  must(os.Setenv("HOME",home));must(os.Setenv("USERPROFILE",home))
  root:=filepath.Join(home,".many-ai-cli");must(os.MkdirAll(root,0700))
  encodedRoot,e:=json.Marshal(root);must(e);rootJSON:=string(encodedRoot[1:len(encodedRoot)-1])
  expand:=func(text string)string{return strings.ReplaceAll(strings.ReplaceAll(text,`\u003croot\u003e`,rootJSON),"<root>",rootJSON)}
  b,e:=json.Marshal(c.Initial);must(e);must(json.Unmarshal([]byte(expand(string(b))),&c.Initial))
  cfg:=&config.Config{UserPrefs:c.Initial}
  cfg.UserPrefs.UsageProbeModel=config.EffectiveUsageProbeModel(cfg.UserPrefs.UsageProbeModel)
  for i:=0;i<c.Backends;i++ {cfg.Notify.Backends=append(cfg.Notify.Backends,config.NotifyBackendConfig{})}
  s:=&Server{cfg:cfg,logger:slog.New(slog.NewTextHandler(io.Discard,nil))}
  if c.Push>0 {s.push=&pushManager{c.Push}}
  if c.FailSave {must(os.Mkdir(filepath.Join(root,"config.yaml"),0700))}
  original:=userPrefsTemplateVersion(cfg.UserPrefs.Templates)
  r:=httptest.NewRequest(c.Method,"http://127.0.0.1:49961/api/user-prefs",strings.NewReader(expand(c.Body)))
  r.Header.Set("X-Template-Write",c.Policy)
  version:=c.Version;if version=="current" {version=original};r.Header.Set("X-Template-Version",version)
  w:=httptest.NewRecorder();s.handleUserPrefs(w,r)
  normalize:=func(text string)string{return regexp.MustCompile(`config-[0-9]+\.yaml\.tmp`).ReplaceAllString(strings.ReplaceAll(text,rootJSON,"<root>"),"config-<temporary>.yaml.tmp")}
  projected:=func(value any)any{bytes,e:=json.Marshal(value);must(e);var v any;d:=json.NewDecoder(strings.NewReader(normalize(string(bytes))));d.UseNumber();must(d.Decode(&v));return v}
  var body any;decoder:=json.NewDecoder(strings.NewReader(w.Body.String()));decoder.UseNumber();must(decoder.Decode(&body));body=projected(body)
  // Failure detail includes platform IO text. Keep the stable source error class.
  if w.Code==500 {body.(map[string]any)["detail"]="save failed: <owned filesystem error>"}
  var saved any
  if bytes,e:=os.ReadFile(filepath.Join(root,"config.yaml"));e==nil {var loaded config.Config;must(yaml.Unmarshal(bytes,&loaded));saved=projected(loaded.UserPrefs)}
  rows=append(rows,map[string]any{"name":c.Name,"status":w.Code,"body":body,"content_type":w.Header().Get("Content-Type"),"version":w.Header().Get("X-Template-Version"),"initial_version":original,"runtime":projected(s.cfg.UserPrefs),"saved":saved})
  must(os.RemoveAll(home))
 }
 encoder:=json.NewEncoder(os.Stdout);encoder.SetIndent("","  ");must(encoder.Encode(rows))
}
