#!/usr/bin/env python3
"""Extract fixed-Go pure handlers into an offline, synthetic observation tool.

Writes only go_oracle.go beside this script. Run the generated filename with
Go, capturing stdout as go_oracle.json. No server, token, real home or provider
is used. Signatures use a local three-field projection of proto.ApprovalSummary;
functions and BatchRequest are extracted from the pinned Git objects.
"""
from pathlib import Path
import subprocess

SHA = "21d0bc7935a2c4696fb89ccff2e324157a528c2d"
ROOT = Path(__file__).resolve().parents[5]
OUT = Path(__file__).resolve().parent

def source(path):
    return subprocess.check_output(["git", "show", f"{SHA}:{path}"], cwd=ROOT, text=True)

def declaration(text, prefix):
    start = text.index(prefix)
    end = text.index("\n}\n", start) + 3
    return text[start:end]

action = source("internal/hub/approval_action.go")
batch = source("internal/hub/approval_batch.go")
http = source("internal/hub/http_helpers.go")
parts = [
    declaration(batch, "type approvalBatchRequest struct"),
    declaration(batch, "func approvalBatchSignature").replace("proto.ApprovalSummary", "approvalSummary"),
    declaration(action, "func (s *Server) writeOneTapApprovalError"),
    declaration(action, "func (m *oneTapApprovalManager) consume"),
    declaration(http, "func decodeJSON"),
    declaration(http, "func writeJSONStatus"),
    declaration(http, "type httpErrorResp struct"),
    declaration(http, "func writeJSONError"),
]
header = '''//go:build ignore

// Generated by generate_oracle.py from fixed Go SHA ''' + SHA + '''.
// Extracted source helpers; only local DTO projection/harness below is synthetic.
package main
import (
 "encoding/json"
 "errors"
 "net/http"
 "net/http/httptest"
 "os"
 "strings"
 "sync"
 "time"
)
const jsonBodyMaxBytes = 1024 * 1024
type Server struct{}
type approvalSummary struct { Command string; Risk string }
type oneTapApprovalClaim struct { ExpiresAt int64; Nonce string }
type oneTapApprovalManager struct { mu sync.Mutex; used map[string]time.Time; now func() time.Time }
var (
 errOneTapInvalid = errors.New("invalid")
 errOneTapExpired = errors.New("expired")
 errOneTapConsumed = errors.New("consumed")
 errOneTapHighRisk = errors.New("high risk")
 errOneTapNoApproval = errors.New("no approval")
)
'''
harness = r'''
func main() {
 out := map[string]any{"oracle": "21d0bc7935a2c4696fb89ccff2e324157a528c2d"}
 errorRows := []any{}
 for _, item := range []struct{Name string; Err error}{
  {"invalid",errOneTapInvalid}, {"expired",errOneTapExpired}, {"consumed",errOneTapConsumed},
  {"high_risk",errOneTapHighRisk}, {"not_pending",errOneTapNoApproval}, {"other",errors.New("synthetic")},
 } {
  w := httptest.NewRecorder(); (&Server{}).writeOneTapApprovalError(w,item.Err)
  var body any; json.Unmarshal(w.Body.Bytes(), &body)
  errorRows = append(errorRows,map[string]any{"name":item.Name,"status":w.Code,"body":body})
 }
 out["errors"] = errorRows
 decodeRows := []any{}
 for _, input := range []string{
  `null`, `{}`, `{"SIGNATURE":"group","ACTION":"approve","SESSION_ID":null}`,
  `{"signature":"first","signature":null,"action":"approve"}`,
  `{"signature":"first","signature":"last","action":"approve"} trailing`,
  `{"signature":5,"signature":"later"}`, `{"session_id":1.5}`, `[]`, `{`,
  `{"signature":"group","action":"deny_session","session_id":2,"unknown":1e999}`,
  `{"signature":"group","action":"approve"}{"action":"auto_rule"}`,
 } {
  var req approvalBatchRequest
  w := httptest.NewRecorder(); r := httptest.NewRequest("POST","http://127.0.0.1/",strings.NewReader(input))
  ok := decodeJSON(w,r,&req)
  row := map[string]any{"input":input,"ok":ok}
  if ok { row["signature"]=req.Signature; row["action"]=req.Action; row["session_id"]=req.SessionID }
  decodeRows = append(decodeRows,row)
 }
 out["decode"] = decodeRows
 signatureRows := []any{}
 for _, x := range []struct { Provider,Command,Risk,CWD string }{
  {" CODEX "," git status ","low"," /synthetic/project "},
  {"İ","a\u0000b","mid","/synthetic/é"},
  {"\u2003CLAUDE\u2003","cmd"," low ","\u0085/x\u0085"},
 } { signatureRows = append(signatureRows,map[string]any{"provider":x.Provider,"command":x.Command,"risk":x.Risk,"cwd":x.CWD,"signature":approvalBatchSignature(x.Provider,x.CWD,approvalSummary{x.Command,x.Risk})}) }
 out["signatures"] = signatureRows
 expiryRows := []any{}
 for _, nanos := range []int64{-1,0,1} {
  at := time.Unix(1700000120,nanos)
  m := &oneTapApprovalManager{used:map[string]time.Time{},now:func()time.Time{return at}}
  claim := oneTapApprovalClaim{ExpiresAt:1700000120,Nonce:"synthetic"}
  err := m.consume(claim)
  code := "ok"; if err != nil {code=err.Error()}
  expiryRows=append(expiryRows,map[string]any{"offset_nanos":nanos,"result":code,"used":len(m.used)})
 }
 out["expiry"] = expiryRows
 encoder:=json.NewEncoder(os.Stdout); encoder.SetIndent("","  "); if err:=encoder.Encode(out); err!=nil {panic(err)}
}
'''
(OUT / "go_oracle.go").write_text(header + "\n".join(parts) + harness)
