//go:build ignore

// Generated by generate_oracle.py from fixed Go SHA 21d0bc7935a2c4696fb89ccff2e324157a528c2d.
// Extracted source helpers; only local DTO projection/harness below is synthetic.
package main

import (
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"sync"
	"time"
)

const jsonBodyMaxBytes = 1024 * 1024

type Server struct{}
type approvalSummary struct {
	Command string
	Risk    string
}
type oneTapApprovalClaim struct {
	ExpiresAt int64
	Nonce     string
}
type oneTapApprovalManager struct {
	mu   sync.Mutex
	used map[string]time.Time
	now  func() time.Time
}

var (
	errOneTapInvalid    = errors.New("invalid")
	errOneTapExpired    = errors.New("expired")
	errOneTapConsumed   = errors.New("consumed")
	errOneTapHighRisk   = errors.New("high risk")
	errOneTapNoApproval = errors.New("no approval")
)

type approvalBatchRequest struct {
	Signature string `json:"signature"`
	Action    string `json:"action"`
	SessionID int    `json:"session_id,omitempty"`
}

func approvalBatchSignature(provider, cwd string, summary approvalSummary) string {
	return strings.ToLower(strings.TrimSpace(provider)) + "\x00" +
		strings.TrimSpace(summary.Command) + "\x00" + string(summary.Risk) + "\x00" + strings.TrimSpace(cwd)
}

func (s *Server) writeOneTapApprovalError(w http.ResponseWriter, err error) {
	switch {
	case errors.Is(err, errOneTapConsumed):
		writeJSONError(w, http.StatusConflict, "action_already_used", "action already used")
	case errors.Is(err, errOneTapExpired), errors.Is(err, errOneTapInvalid):
		writeJSONError(w, http.StatusUnauthorized, "invalid_action_token", "invalid or expired action token")
	case errors.Is(err, errOneTapHighRisk):
		writeJSONError(w, http.StatusForbidden, "high_risk_requires_in_app_confirmation", "open Hub to confirm this high-risk approval")
	case errors.Is(err, errOneTapNoApproval):
		writeJSONError(w, http.StatusConflict, "approval_not_pending", "approval is no longer pending")
	default:
		writeJSONError(w, http.StatusConflict, "action_not_applied", "approval action was not applied")
	}
}

func (m *oneTapApprovalManager) consume(claim oneTapApprovalClaim) error {
	if m == nil {
		return errOneTapInvalid
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	now := m.now()
	for nonce, expires := range m.used {
		if !expires.After(now) {
			delete(m.used, nonce)
		}
	}
	if claim.ExpiresAt <= now.Unix() {
		return errOneTapExpired
	}
	if _, exists := m.used[claim.Nonce]; exists {
		return errOneTapConsumed
	}
	m.used[claim.Nonce] = time.Unix(claim.ExpiresAt, 0)
	return nil
}

func decodeJSON(w http.ResponseWriter, r *http.Request, dst any) bool {
	dec := json.NewDecoder(http.MaxBytesReader(w, r.Body, jsonBodyMaxBytes))
	if err := dec.Decode(dst); err != nil {
		writeJSONError(w, http.StatusBadRequest, "bad_request", "invalid json")
		return false
	}
	return true
}

func writeJSONStatus(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	if status != http.StatusOK {
		w.WriteHeader(status)
	}
	_ = json.NewEncoder(w).Encode(v)
}

type httpErrorResp struct {
	OK     bool   `json:"ok"`
	Error  string `json:"error"`
	Detail string `json:"detail,omitempty"`
}

func writeJSONError(w http.ResponseWriter, status int, code, detail string) {
	if code == "" {
		code = "error"
	}
	if detail == "" {
		detail = http.StatusText(status)
	}
	writeJSONStatus(w, status, httpErrorResp{
		OK:     false,
		Error:  code,
		Detail: detail,
	})
}

func main() {
	out := map[string]any{"oracle": "21d0bc7935a2c4696fb89ccff2e324157a528c2d"}
	errorRows := []any{}
	for _, item := range []struct {
		Name string
		Err  error
	}{
		{"invalid", errOneTapInvalid}, {"expired", errOneTapExpired}, {"consumed", errOneTapConsumed},
		{"high_risk", errOneTapHighRisk}, {"not_pending", errOneTapNoApproval}, {"other", errors.New("synthetic")},
	} {
		w := httptest.NewRecorder()
		(&Server{}).writeOneTapApprovalError(w, item.Err)
		var body any
		json.Unmarshal(w.Body.Bytes(), &body)
		errorRows = append(errorRows, map[string]any{"name": item.Name, "status": w.Code, "body": body})
	}
	out["errors"] = errorRows
	decodeRows := []any{}
	for _, input := range []string{
		`null`, `{}`, `{"SIGNATURE":"group","ACTION":"approve","SESSION_ID":null}`,
		`{"signature":"first","signature":null,"action":"approve"}`,
		`{"signature":"first","signature":"last","action":"approve"} trailing`,
		`{"signature":5,"signature":"later"}`, `{"session_id":1.5}`, `[]`, `{`,
		`{"signature":"group","action":"deny_session","session_id":2,"unknown":1e999}`,
		`{"signature":"group","action":"approve"}{"action":"auto_rule"}`,
	} {
		var req approvalBatchRequest
		w := httptest.NewRecorder()
		r := httptest.NewRequest("POST", "http://127.0.0.1/", strings.NewReader(input))
		ok := decodeJSON(w, r, &req)
		row := map[string]any{"input": input, "ok": ok}
		if ok {
			row["signature"] = req.Signature
			row["action"] = req.Action
			row["session_id"] = req.SessionID
		}
		decodeRows = append(decodeRows, row)
	}
	out["decode"] = decodeRows
	signatureRows := []any{}
	for _, x := range []struct{ Provider, Command, Risk, CWD string }{
		{" CODEX ", " git status ", "low", " /synthetic/project "},
		{"İ", "a\u0000b", "mid", "/synthetic/é"},
		{"\u2003CLAUDE\u2003", "cmd", " low ", "\u0085/x\u0085"},
	} {
		signatureRows = append(signatureRows, map[string]any{"provider": x.Provider, "command": x.Command, "risk": x.Risk, "cwd": x.CWD, "signature": approvalBatchSignature(x.Provider, x.CWD, approvalSummary{x.Command, x.Risk})})
	}
	out["signatures"] = signatureRows
	expiryRows := []any{}
	for _, nanos := range []int64{-1, 0, 1} {
		at := time.Unix(1700000120, nanos)
		m := &oneTapApprovalManager{used: map[string]time.Time{}, now: func() time.Time { return at }}
		claim := oneTapApprovalClaim{ExpiresAt: 1700000120, Nonce: "synthetic"}
		err := m.consume(claim)
		code := "ok"
		if err != nil {
			code = err.Error()
		}
		expiryRows = append(expiryRows, map[string]any{"offset_nanos": nanos, "result": code, "used": len(m.used)})
	}
	out["expiry"] = expiryRows
	encoder := json.NewEncoder(os.Stdout)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(out); err != nil {
		panic(err)
	}
}
